name: RailGun Auto Checkin

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  glados:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -u -m pip install --upgrade pip
          python -u -m pip install playwright requests pynacl matplotlib
          python -u -m playwright install chromium

      - name: Run RailGun auto login & checkin
        env:
          RAILGUN_EMAIL: ${{ vars.RAILGUN_EMAIL }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          RAILGUN_LOCAL: ${{ secrets.RAILGUN_LOCAL }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python -u railgun/railgun_1.py
